# Generated by Django 4.0.3 on 2022-03-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='effort',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9)], default=5),
        ),
    ]
