# Generated by Django 4.0.3 on 2022-04-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_historicalworkout_delete_workoutmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkout',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
