# Generated by Django 4.0.3 on 2022-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
