# Generated by Django 4.0.3 on 2022-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_weight_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='lbs',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
