# Generated by Django 4.0.3 on 2022-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_weight_lbs'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weight',
            constraint=models.UniqueConstraint(fields=('entry_date', 'profile'), name='unique_weight_by_day_for_user_profile'),
        ),
    ]
