# Generated by Django 4.0.3 on 2022-04-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_weight_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='dashboard.profile'),
        ),
    ]
