# Generated by Django 4.0.3 on 2022-04-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_weight_profile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weight',
            constraint=models.UniqueConstraint(fields=('profile', 'entry_date'), name='unique_weight_entry_per_date_and_profife'),
        ),
    ]
