# Generated by Django 4.0.3 on 2022-04-06 11:26

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_weight_unique_weight_entry_per_date_and_profife'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weight',
            name='unique_weight_entry_per_date_and_profife',
        ),
        migrations.AddConstraint(
            model_name='weight',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('profile', 'entry_date'), name='unique_weight_entry_per_date_and_profife'),
        ),
    ]
