# Generated by Django 4.0.3 on 2022-04-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_weight_unique_weight_entry_per_date_and_profife_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weight',
            name='unique_weight_entry_per_date_and_profife',
        ),
    ]
